# Singular Value Decomposition (SVD) in Python
Singular Value Decomposition (SVD) is a fundamental matrix factorization technique used in linear algebra, data compression, and machine learning.

SVD decomposes a matrix \( A \) into three matrices:

\[ A = U \Sigma V^T \]

Where:
- \( U \) is an orthogonal matrix (left singular vectors)
- \( \Sigma \) is a diagonal matrix (singular values)
- \( V^T \) is the transpose of an orthogonal matrix (right singular vectors)


## Step 1: Import Libraries
We use NumPy to perform SVD.

## Step 2: Define SVD Function
We define a function to compute SVD using `numpy.linalg.svd()` and construct the diagonal matrix \( \Sigma \) from singular values.

## Step 3: Example Matrix
We define a sample matrix and compute its SVD.

## Step 4: Reconstruct the Original Matrix
We verify the decomposition by reconstructing the original matrix using \( U \Sigma V^T \).

In [1]:
import numpy as np

def compute_svd(A):
    """
    Compute Singular Value Decomposition of matrix A.
    :param A: Input matrix
    :return: U, Sigma, V^T matrices
    """
    U, S, Vt = np.linalg.svd(A)
    Sigma = np.zeros((A.shape[0], A.shape[1]))
    np.fill_diagonal(Sigma, S)
    
    return U, Sigma, Vt

In [2]:
# Example usage
A = np.array([[3, 2, 2], [2, 3, -2]])
U, Sigma, Vt = compute_svd(A)

print("Original Matrix:")
print(A)
print("\nU Matrix:")
print(U)
print("\nSigma Matrix:")
print(Sigma)
print("\nV^T Matrix:")
print(Vt)

Original Matrix:
[[ 3  2  2]
 [ 2  3 -2]]

U Matrix:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Sigma Matrix:
[[5. 0. 0.]
 [0. 3. 0.]]

V^T Matrix:
[[ 7.07106781e-01  7.07106781e-01  3.67439059e-16]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


In [3]:
# Verification
reconstructed_A = U @ Sigma @ Vt
print("\nReconstructed A:")
print(reconstructed_A)


Reconstructed A:
[[ 3.  2.  2.]
 [ 2.  3. -2.]]
